# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 12:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rue', models.CharField(blank=True, max_length=80, null=True)),
                ('no', models.CharField(blank=True, max_length=8, null=True)),
                ('visavis', models.CharField(blank=True, help_text='Exemple: à côté restaurant Cercle Vert', max_length=150, null=True)),
                ('expliq', models.TextField(blank=True, help_text='Explication supplémentaire.', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Arrivage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('designation', models.CharField(max_length=30, verbose_name='désignation')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=80)),
                ('nom', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, help_text='Email du contact', max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, help_text='Email entreprise', max_length=254, null=True)),
                ('adresse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinates.Adresse')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinates.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, verbose_name='Lieu')),
                ('npa', models.CharField(blank=True, help_text="No postal d'acheminement", max_length=8, null=True, verbose_name='NPA')),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Cameroun', max_length=80)),
                ('code', models.CharField(default='N.D.', max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Format: '+999999999'. Maximum 15 chiffres.", regex='^\\+?1?\\d{9,15}$')])),
                ('phone_type', models.CharField(choices=[(1, 'Mobile'), (2, 'Bureau'), (3, 'Domicile')], default=1, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coordinates.Phone')),
            ],
            bases=('coordinates.phone',),
        ),
        migrations.AddField(
            model_name='localite',
            name='pays',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinates.Pays'),
        ),
    ]
