# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0002_auto_20170630_1428'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pays',
            unique_together=set([('nom', 'code')]),
        ),
    ]
