# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0003_auto_20170701_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localite',
            name='nom',
            field=models.CharField(max_length=80, verbose_name='Lieu'),
        ),
    ]
