# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0006_auto_20170711_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localite',
            name='nom',
            field=models.CharField(max_length=80, unique=True, verbose_name='Lieu'),
        ),
    ]
