# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordinates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('objet', models.CharField(max_length=80, null=True)),
                ('quantite', models.IntegerField()),
                ('date_achat', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=3, unique=True)),
                ('rate_usd', models.DecimalField(decimal_places=4, default=1.0, editable=False, max_digits=15)),
                ('last_update', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Frais_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='FraisArrivage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('objet', models.CharField(default='', max_length=80)),
                ('date_frais', models.DateField(default=django.utils.timezone.now)),
                ('arrivage_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinates.Arrivage')),
                ('devise_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Currency')),
                ('frais_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Frais_Type')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Frais',
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_vente_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('achat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Achat')),
            ],
        ),
        migrations.AddField(
            model_name='achat',
            name='devise_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance.Currency'),
        ),
    ]
