# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20170630_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fraisarrivage',
            options={'ordering': ['arrivage_ref', '-date_frais']},
        ),
    ]
