# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20170711_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='currency_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
