# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('coordinates', '0001_initial'),
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='arrivage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinates.Arrivage'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='categories',
            field=mptt.fields.TreeManyToManyField(to='accessories.AccessoryCategory', verbose_name='Catégorie accessoire'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='marque_ref',
            field=models.ForeignKey(blank=True, help_text='Choix des marques', null=True, on_delete=django.db.models.deletion.CASCADE, to='accessories.AccessoryMarque'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='prix_achat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Achat', verbose_name="Prix d'achat unitaire"),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryaccessory',
            unique_together=set([('date', 'article')]),
        ),
    ]
