# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0002_auto_20170630_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'permissions': (('view_achat', 'Can view achats'),), 'verbose_name': 'Accessoire'},
        ),
    ]
