# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0003_auto_20170711_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='date_ajout',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
