# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('coordinates', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryShoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='shoes')),
                ('legende', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_client', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('E', 'Enfant')], default='F', max_length=1)),
                ('name', models.CharField(max_length=100, verbose_name='Nom du modèle')),
                ('arrivage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinates.Arrivage')),
            ],
            options={
                'verbose_name': 'Chaussures',
            },
        ),
        migrations.CreateModel(
            name='ShoeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.ShoeCategory')),
            ],
            options={
                'ordering': ['tree_id', 'lft'],
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='ShoeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name="Date de l'arrivage")),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.Shoe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShoeOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.Shoe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='shoe',
            name='categories',
            field=mptt.fields.TreeManyToManyField(to='shoes.ShoeCategory', verbose_name='Catégories'),
        ),
        migrations.AddField(
            model_name='shoe',
            name='marque_ref',
            field=models.ForeignKey(blank=True, help_text='Choix des marques', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Marque'),
        ),
        migrations.AddField(
            model_name='shoe',
            name='prix_achat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Achat', verbose_name="Prix d'achat unitaire"),
        ),
        migrations.AddField(
            model_name='photo',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.Shoe'),
        ),
        migrations.AddField(
            model_name='inventoryshoe',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.Shoe'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryshoe',
            unique_together=set([('date', 'article')]),
        ),
    ]
